apiVersion: v1
kind: Service
metadata:
  labels:
    app: assignment-service-v2
    type: microservice
    tier: backend
  name: assignment-service-v2
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: assignment-service-v2
  type: NodePort

