apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: data2graph-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /data2graph(/|$)(.*)
            backend:
              serviceName: data2graph-service
              servicePort: 80