spring:
  data:
    mongodb:
      uri: mongodb://root:Root_123@172.16.10.101:27017/plagiarism-service-db?authSource=admin
      database: plagiarism-service-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/assessment-system-ff99e
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
  rabbitmq:
    addresses: 172.16.10.103
    port: 5672
server:
  port: 8080
