spring:
  data:
    mongodb:
      uri: mongodb://192.168.0.2:27017/classroom-service-db?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/assessment-system-ff99e
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

#server:
#  servlet:
#    context-path: /api/classrooms/