apiVersion: v1
kind: Service
metadata:
  labels:
    app: moss-api-service
    type: microservice
    tier: backend
  name: moss-api-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8082
  selector:
    app: moss-api-service
  type: NodePort